name: Java Application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven 
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  push-job:
  
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Build & Push Image
      env:
          DOCKER_TOKEN: ${{ env.DOCKER_TOKEN }}
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWD }}" | docker login -u "wseyi" --password-stdin
        docker image build -t wseyi/java-sample:latest .
        docker push wseyi/java-sample:latest
